# Generated by Django 6.0.4 on 2026-04-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_title_user_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='config/logos/')),
                ('hero_image', models.ImageField(upload_to='config/hero/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('sub_slogan', models.CharField(blank=True, max_length=255)),
                ('footer_info', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='accounts.clinic')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
