# Generated by Django 6.0.4 on 2026-04-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='hero_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
