# Generated by Django 6.0.4 on 2026-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_configuration_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
