# Generated by Django 6.0.4 on 2026-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_configuration_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
