# Generated by Django 6.0.4 on 2026-04-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_from_time_user_to_time_user_vacation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vacation_days',
        ),
    ]
