# Generated by Django 6.0.4 on 2026-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_doctor_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('view_inventory', 'View Inventory'), ('edit_inventory', 'Edit Inventory'), ('add_inventory', 'Add Inventory'), ('delete_inventory', 'Delete Inventory'), ('view_config', 'View Configurations'), ('edit_config', 'Edit Configurations'), ('view_doctor', 'View Doctor'), ('add_doctor', 'Add Doctor'), ('edit_doctor', 'Edit Doctor'), ('delete_doctor', 'Delete Doctor'), ('view_branch', 'View Branch'), ('add_branch', 'Add Branch'), ('edit_branch', 'Edit Branch'), ('delete_branch', 'Delete Branch'), ('view_patient', 'View Patient'), ('add_patient', 'Add Patient'), ('edit_patient', 'Edit Patient'), ('delete_patient', 'Delete Patient')], max_length=30, unique=True)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-user__date_joined']},
        ),
    ]
