# Generated by Django 6.0.4 on 2026-04-20 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_seed_assistant_roles'),
        ('branches', '0009_remove_doctorschedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='branches.branch')),
                ('roles', models.ManyToManyField(blank=True, related_name='assistants', to='accounts.assistantrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
