# Generated by Django 6.0.4 on 2026-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_assistant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='slot_interval',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
