# Generated by Django 6.0.4 on 2026-04-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('veil', 'Veil'), ('syringe', 'Syringe')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
