# Generated by Django 6.0.4 on 2026-04-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('pulses', 'Pulses'), ('duration', 'Duration'), ('injectables', 'Injectables'), ('sessions', 'Sessions')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='accounts.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
