# Generated by Django 6.0.4 on 2026-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('injectable', 'Injectable'), ('machine', 'Machine')], default='injectable', max_length=20),
        ),
    ]
