# Generated by Django 6.0.4 on 2026-04-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantrole',
            name='role_name',
            field=models.CharField(choices=[('view_inventory', 'View Inventory'), ('edit_inventory', 'Edit Inventory'), ('add_inventory', 'Add Inventory'), ('delete_inventory', 'Delete Inventory'), ('view_config', 'View Configurations'), ('edit_config', 'Edit Configurations'), ('view_doctor', 'View Doctor'), ('add_doctor', 'Add Doctor'), ('edit_doctor', 'Edit Doctor'), ('delete_doctor', 'Delete Doctor'), ('view_branch', 'View Branch'), ('add_branch', 'Add Branch'), ('edit_branch', 'Edit Branch'), ('delete_branch', 'Delete Branch'), ('view_patient', 'View Patient'), ('add_patient', 'Add Patient'), ('edit_patient', 'Edit Patient'), ('delete_patient', 'Delete Patient'), ('view_appointment', 'View Appointments'), ('add_appointment', 'Add Appointments'), ('edit_appointment', 'Edit Appointments'), ('delete_appointment', 'Delete Appointments')], max_length=30, unique=True),
        ),
    ]
