# Generated by Django 6.0.4 on 2026-05-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_update_pulse_area_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='latest_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
