# Generated by Django 6.0.4 on 2026-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_machine_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price_per_consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price_per_examination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
