# Generated by Django 6.0.4 on 2026-05-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_add_doctor_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concentration', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.doctor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
