# Generated by Django 6.0.4 on 2026-05-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_doctor_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_services', to='accounts.doctor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
