# Generated by Django 6.0.4 on 2026-05-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_general_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remainder_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
