# Generated by Django 6.0.4 on 2026-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_product_remainder_ml'),
        ('branches', '0009_remove_doctorschedule_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='branch',
        ),
        migrations.AddField(
            model_name='assistant',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='branches.branch'),
        ),
    ]
