# Generated by Django 6.0.4 on 2026-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_assistant_branch_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalservice',
            name='clinic_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='generalservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
