# Generated by Django 6.0.4 on 2026-07-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_add_clinic_fees_to_general_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalservice',
            name='price',
        ),
    ]
