# Generated by Django 6.0.4 on 2026-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_price_add_general_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
