# Generated by Django 6.0.4 on 2026-07-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_add_price_back_to_general_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalservice',
            old_name='price',
            new_name='general_service_price',
        ),
    ]
