# Generated by Django 6.0.4 on 2026-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_payment_info_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='clinic_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
