# Generated by Django 6.0.4 on 2026-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_area_branch_city_branch_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
