# Generated by Django 6.0.4 on 2026-04-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_branch_email_alter_branch_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='area',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_time',
        ),
    ]
