# Generated by Django 6.0.4 on 2026-04-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_remove_branch_area_remove_branch_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='vacation_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
