# Generated by Django 6.0.4 on 2026-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_from_time_branch_to_time_branch_vacation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbranchassignment',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbranchassignment',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbranchassignment',
            name='vacation_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
