# Generated by Django 6.0.4 on 2026-04-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_doctorschedule_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['branch', 'day', 'from_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
    ]
