# Generated by Django 6.0.4 on 2026-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
