# Generated by Django 6.0.4 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_patient_medical_notes'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE appointments_patient SET date_of_birth = '1900-01-01' WHERE date_of_birth IS NULL",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
