# Generated by Django 6.0.4 on 2026-04-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_make_patient_fields_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinic_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visit_date',
        ),
    ]
