# Generated by Django 6.0.4 on 2026-04-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_reservation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
