# Generated by Django 6.0.4 on 2026-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_update_pulse_area_packages'),
        ('appointments', '0007_patient_family_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='area_packages',
            field=models.ManyToManyField(blank=True, related_name='patients', to='accounts.areapackage'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pulse_packages',
            field=models.ManyToManyField(blank=True, related_name='patients', to='accounts.pulsepackage'),
        ),
    ]
