# Generated by Django 6.0.4 on 2026-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_reservation_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
