# Generated by Django 6.0.4 on 2026-05-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_add_finished_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_examination',
            field=models.BooleanField(default=False),
        ),
    ]
