# Generated by Django 6.0.4 on 2026-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_add_examination_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationattachment',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservationattachment',
            name='file',
            field=models.FileField(blank=True, upload_to='reservation_attachments/'),
        ),
    ]
