# Generated by Django 6.0.4 on 2026-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
