# Generated by Django 6.0.4 on 2026-05-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_doctor_medicine'),
        ('appointments', '0013_add_attachment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermaFaceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(default='face', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derma_mappings', to='appointments.patient')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derma_mappings', to='appointments.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DermaFaceMappingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('zone_label', models.CharField(max_length=100)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='appointments.dermafacemapping')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.service')),
            ],
            options={
                'ordering': ['zone_id'],
            },
        ),
        migrations.CreateModel(
            name='DermaFaceMappingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(max_length=20)),
                ('product_type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=50)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('pulses', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.machine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='appointments.dermafacemappingzone')),
            ],
        ),
    ]
