# Generated by Django 6.0.4 on 2026-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_restructure_derma_zone_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dermafacemappingline',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dermafacemappingzoneservice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
