# Generated by Django 6.0.4 on 2026-05-19 18:59

from django.db import migrations, models

ZONES = [
    (1, 'Forehead'),
    (2, 'Right cheek'),
    (3, 'Left cheek'),
    (4, 'Nose'),
    (5, 'Upper lip'),
    (6, 'Lower lip'),
    (7, 'Chin'),
    (8, 'Hair'),
]


def seed_zones(apps, schema_editor):
    ZoneDefinition = apps.get_model('appointments', 'ZoneDefinition')
    ZoneDefinition.objects.all().delete()
    ZoneDefinition.objects.bulk_create([
        ZoneDefinition(zone_id=z_id, zone_label=label) for z_id, label in ZONES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_increase_volume_ml_max_digits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True)),
                ('zone_label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['zone_id'],
            },
        ),
        migrations.RunPython(seed_zones, migrations.RunPython.noop),
    ]
