# Generated by Django 6.0.4 on 2026-05-19 19:29

import django.db.models.deletion
from django.db import migrations, models

BODY_ZONES = [
    (1, 'Abdomen'),
    (2, 'Right hand'),
    (3, 'Left hand'),
    (4, 'Right leg'),
    (5, 'Left leg'),
]


def seed_body_zones(apps, schema_editor):
    BodyZoneDefinition = apps.get_model('appointments', 'BodyZoneDefinition')
    BodyZoneDefinition.objects.bulk_create([
        BodyZoneDefinition(zone_id=z_id, zone_label=label) for z_id, label in BODY_ZONES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_general_service'),
        ('appointments', '0017_add_zone_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyZoneDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True)),
                ('zone_label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['zone_id'],
            },
        ),
        migrations.CreateModel(
            name='DermaBodyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(default='body', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_mappings', to='appointments.patient')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_mappings', to='appointments.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DermaBodyMappingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('zone_label', models.CharField(max_length=100)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='appointments.dermabodymapping')),
            ],
            options={
                'ordering': ['zone_id'],
            },
        ),
        migrations.CreateModel(
            name='DermaBodyMappingZoneService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.service')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_services', to='appointments.dermabodymappingzone')),
            ],
        ),
        migrations.RunPython(seed_body_zones, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DermaBodyMappingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(max_length=20)),
                ('product_type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=50)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('pulses', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.machine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
                ('zone_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='appointments.dermabodymappingzoneservice')),
            ],
        ),
    ]
