# Generated by Django 6.0.4 on 2026-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_general_service'),
        ('appointments', '0019_add_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='general_services',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='accounts.generalservice'),
        ),
    ]
