# Generated by Django 6.0.4 on 2026-06-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_assistant_branch_m2m'),
        ('appointments', '0020_add_reservation_general_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='appointments.patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='appointments.reservation'),
        ),
        migrations.CreateModel(
            name='PatientAreaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='accounts.areapackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_package_records', to='appointments.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPulsePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pulses', models.PositiveIntegerField()),
                ('remaining_pulses', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='accounts.pulsepackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_package_records', to='appointments.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
