# Generated by Django 6.0.4 on 2026-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_add_invoice_paid_amount_partial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('complimentary', 'Complimentary')], default='pending', max_length=20),
        ),
    ]
