# Generated by Django 6.0.4 on 2026-06-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_fix_free_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Instapay'), (2, 'Cash'), (3, 'Visa')], null=True),
        ),
    ]
