# Generated by Django 6.0.4 on 2026-06-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_add_payment_type_to_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.IntegerField(choices=[(1, 'Instapay'), (2, 'Cash'), (3, 'Visa')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.invoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
