# Generated by Django 6.0.4 on 2026-07-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_add_invoice_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='general_service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
