# Generated by Django 6.0.4 on 2026-07-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_payment_info_role'),
        ('appointments', '0028_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGeneralServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.generalservice')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_service_prices', to='appointments.reservation')),
            ],
            options={
                'unique_together': {('reservation', 'general_service')},
            },
        ),
    ]
