# Generated by Django 6.0.4 on 2026-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_reservationgeneralserviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationgeneralserviceprice',
            name='clinic_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
