# Generated by Django 6.0.4 on 2026-08-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0030_reservationgeneralserviceprice_clinic_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
